# waypoints of the path [m]
geometry_msgs/PoseStamped[] target_poses

# an image depicting a map of the area which is covered by the path or which the robot is allowed to drive at for obstacle avoidance
sensor_msgs/Image area_map

# position tolerance at each waypoint, i.e. the acceptable deviation from the given path [m]
float32 path_tolerance

# position tolerance at the goal point (the last point) [m]
float32 goal_position_tolerance

# angular tolerance at the goal point (the last point) [rad]
float32 goal_angle_tolerance
---
# index of the point planned. target_poses.size() if the last one
int32 last_planned_point_index
---
geometry_msgs/PoseStamped base_position
